version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "CODEBUILD_WEBHOOK_TRIGGER: $CODEBUILD_WEBHOOK_TRIGGER"

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
