version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install 
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - |
        echo "BRANCH_NAME: $BRANCH_NAME"
        if [ "$BRANCH_NAME" = "main" ]; then
          aws s3 sync build/ s3://arjit-s3
        elif [ "$BRANCH_NAME" = "dev" ]; then
          aws s3 sync build/ s3://lucifer-wsr
        else
          echo "No S3 bucket specified for this branch."
          exit 1
        fi

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
