version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" == "main" ]; then
          # Use rsync to upload new or modified build artifacts to the S3 bucket
          aws s3 sync build/ s3://wsr-frontend-testing/  

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
