version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" == "PUSH" ]; then
          case "$CODEBUILD_SOURCE_BRANCH" in
            "main")
              aws s3 sync build/ s3://wsr-frontend-testing 
              ;;
            "branch2")
              aws s3 sync build/ s3://bucket2 --exclude ".htaccess" --delete
              ;;
            "branch3")
              aws s3 sync build/ s3://bucket3 --exclude ".htaccess" --delete
              ;;
            *)
              echo "No matching branch for deployment."
              ;;
          esac
        else
          echo "Not a push event. Skipping deployment."
        fi
artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
