version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - |
        if [ "$BRANCH_NAME_MAIN" == "main" ]; then
          aws s3 sync build/ s3://wsr-frontend-testing
        elif [ "$BRANCH_NAME_DEV" == "dev" ]; then
          aws s3 sync build/ s3://bucket-2
        else
          echo "No S3 bucket specified for this branch."
          exit 1
        f
artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
